[package]
name = "libra-crypto-sgx"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra libra-crypto"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
libra-crypto-derive = { path = "../crypto-derive", version = "0.1.0", package="libra-crypto-derive-sgx"}
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git"}
rand = {git = "https://github.com/mesalock-linux/rand-sgx.git", tag = "sgx_1.1.2"}
thiserror = { git = "https://github.com/mesalock-linux/thiserror-sgx.git", tag = "sgx_1.1.2" }
serde = {git = "https://github.com/mesalock-linux/serde-sgx.git", tag = "sgx_1.1.2", features = ["derive"]}
serde_bytes = {git = "https://github.com/mesalock-linux/serde-bytes-sgx.git", tag = "sgx_1.1.2"}
serde-name = "0.1.0"
anyhow = {git = "https://github.com/mesalock-linux/anyhow-sgx.git", tag = "sgx_1.1.2" }
lcs = { path = "../../lcs-sgx", version = "0.1.0", package = "libra-canonical-serialization-sgx" }
#bytes = "0.5.5"
bytes = {git = "https://github.com/mesalock-linux/bytes-sgx.git", tag = "sgx_1.1.2" }
curve25519-dalek = { git = "https://github.com/novifinancial/curve25519-dalek.git", branch = "fiat2", default-features = false }
digest = "0.9.0"
ed25519-dalek = { git = "https://github.com/calibra/ed25519-dalek.git", branch = "fiat2", features = ["serde"], default-features = false }
hex = "0.4.2"
hmac = "0.8.1"
once_cell = "1.4.0"
mirai-annotations = {version = "1.8.0", default-features = false }
proptest = { version = "0.10.0", optional = true }
proptest-derive = { version = "0.2.0", optional = true }
#rand_core = { version = "0.5.1", default-features = false }
sha2 = "0.9.1"
static_assertions = { version = "1.1.0", optional = true }
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
sha3 = "0.9.0"
x25519-dalek = { git = "https://github.com/calibra/x25519-dalek.git", branch = "fiat2", default-features = false }
aes-gcm = "0.6.0"
libra-nibble = { path = "../../nibble", version = "0.1.0", package = "libra-nibble-sgx"}
#libra-workspace-hack = { path = "../../common/workspace-hack", version = "0.1.0" }

[dev-dependencies]
bitvec = "0.17.4"
byteorder = "1.3.4"
proptest = "0.10.0"
proptest-derive = "0.2.0"
ripemd160 = "0.9.0"
criterion = "0.3.2"
sha3 = "0.9.0"
serde_json = "1.0.55"

[features]
default = ["std", "fiat_u64_backend"]
assert-private-keys-not-cloneable = ["static_assertions"]
cloneable-private-keys = []
fuzzing = ["proptest", "proptest-derive", "cloneable-private-keys"]
batch = ["ed25519-dalek/batch"]
std = ["curve25519-dalek/std", "ed25519-dalek/std", "x25519-dalek/std"]
u64_backend = ["curve25519-dalek/u64_backend", "ed25519-dalek/u64_backend", "x25519-dalek/u64_backend"]
fiat_u64_backend = ["curve25519-dalek/fiat_u64_backend", "ed25519-dalek/fiat_u64_backend", "x25519-dalek/fiat_u64_backend"]

[[bench]]
name = "hash"
harness = false

[[bench]]
name = "noise"
harness = false
